### ISSUE TITLE
Document lost on page reload

### ISSUE THREAD

**Issue by mikelhamer** [WPS/egon.io#110] opened 2021-12-07 13:15 UTC
Whenever I refresh my browser, everything gets deleted. I have tried on Chrome and Brave browser and it is the same. I can work on a document, creates actors/actions, systems, etc but when the page is reloaded it all disappears.

**Comment by almereyda** [comment] 2023-07-02 14:08
Could this be a duplicate of #64 and #108?

**Comment by hofstef** [comment] 2023-07-05 09:29
> Could this be a duplicate of #64 and #108?

I don't consider this a duplicate; autosave (#64) can reduce the risk of losing the domain story but it does not solve this issue.

**Comment by Geigerkind** [comment] 2023-12-19 09:06
Hey @mikelhamer,
can you please further elaborate your usecase?
Do you have multiple tabs of egon.io open at the same time? Would a restore button of the previous saved draft suffice for your use case?

**Comment by Geigerkind** [comment] 2023-12-21 09:05
Hello @mikelhamer ,
I have revisited this request. I feel like the autosave functionality pretty much implements this functionality. So doing it twice would be a unnecessary. 
What I have done to accommodate your use case better:
* Per default Auto-Save is enabled. Im still debating whether or not it should emit a snackbar everytime it autosaves.
* I reduced the autosave interval. You can configure it in seconds now.
* When refreshing the latest draft will be loaded
* There will be a button to start "fresh" to overwrite this functionality.

So with this I consider this use case served.

**Closed by Geigerkind** 2023-12-21 09:05 UTC
Labels: feature

**Comment by mikelhamer** [comment] 2023-12-21 15:31
> Hello @mikelhamer ,
> 
> I have revisited this request. I feel like the autosave functionality pretty much implements this functionality. So doing it twice would be a unnecessary. 
> 
> What I have done to accommodate your use case better:
> 
> * Per default Auto-Save is enabled. Im still debating whether or not it should emit a snackbar everytime it autosaves.
> 
> * I reduced the autosave interval. You can configure it in seconds now.
> 
> * When refreshing the latest draft will be loaded
> 
> * There will be a button to start "fresh" to overwrite this functionality.
> 
> 
> 
> So with this I consider this use case served.

Thanks. It was quite a while ago now but I recall that when I made this there no working auto save functionality at all. I'm of the opinion that saving should be triggered by every action, data should never be lost.
