### ISSUE TITLE
Object labels are cropped out of PNG exports

### ISSUE THREAD

**Issue by CoeusCC** [WPS/egon.io#71] opened 2019-11-18 14:22 UTC
**Describe the bug**
Object labels are cropped out of PNGs when the item appears at the bottom of the image boundaries.

**To Reproduce**
[example.txt](https://github.com/WPS/domain-story-modeler/files/3858993/example.txt)
(changed extension to .txt because GitHub would not allow the .dst extension)

1. Import the attached .dst
2. Export a PNG
3. Observe the text on the bottom (orange) items is not part of the image

**Expected behavior**
Calculations for the image crop should include some amount of padding for text values

**Screenshots**
![Example PNG](https://user-images.githubusercontent.com/2218833/69059869-629ef700-09e4-11ea-9310-865bb7e069e4.png)

**Desktop (please complete the following information):**
 - Modeler Version: v1.0.1 (master as of today)
 - Browser: Chrome 78
 - OS: Mac

**Additional context**
SVG export does not appear to have this issue.

**Comment by AlexanderZellober** [comment] 2019-12-10 08:25
I've tested this on Windows 10 in Chrome, and it works fine for me. It could take a bit, until I get my hands on a Mac, so I'll remove it from v1.1.0

**Comment by hofstef** [comment] 2020-10-26 15:56
Turns out this is most likely not a Mac issue, but related to the zoom factor. If zoomed out, the PNG export will cut off the labels of work objects (not actors, though) that have more than one line of text. Workaround for the time being: Zoom in a bit before exporting to PNG.

**Comment by Geigerkind** [comment] 2023-12-18 13:21
Hello,
I cant reproduce it. Does the issue still persist?

**Comment by hofstef** [comment] 2024-01-02 15:01
fixed in v2

**Closed by hofstef** 2024-01-02 15:01 UTC
Labels: bug
