### ISSUE TITLE
Save Settings And Domain between Sessions 

### ISSUE THREAD

**Issue by AlexanderZellober** [WPS/egon.io#108] opened 2021-12-01 13:37 UTC
**Is your feature request related to a problem? Please describe.**
Settings and the Domain should be persisted in Browser between Sessions

**Comment by almereyda** [comment] 2023-07-02 14:08
Would it be possible, that this story is a duplicate of #64?

Else, what differentiates it from that?

**Comment by Geigerkind** [comment] 2023-12-20 13:24
Done in v2.

**Closed by Geigerkind** 2023-12-20 13:24 UTC
